import { SessionStarter } from "@/components/session-starter";
import { PremiumMarketDeck } from "@/components/premium-market-deck";
import { Dashboard } from "@/components/dashboard";

/**
 * Home — handoff §2.2.
 *
 * Three entry points: Analyze, Build, Review. Analyze and Build are live; Review is
 * shown as what they will be, marked clearly as not yet available rather than
 * dressed up as working features.
 *
 * Positioning stays research and decision support: no personal amounts, no
 * promised outcomes, the user decides.
 */
/*
 * A returning client sees their own work first; a new visitor sees the pitch.
 * Showing somebody the sales page for the fourth time is a small insult, and
 * the dashboard falls back to this markup whenever there is nothing to show.
 */
export default function HomePage() {
  return <Dashboard onEmpty={<Landing />} />;
}

function Landing() {
  return (
    <main className="landing">
      <section className="hero">
        <div>
          <p className="eyebrow">AI INVESTMENT RESEARCH &amp; DECISION SUPPORT</p>
          <h1>Seven analysts argue.<br />You decide.</h1>
          <p className="lede">
            Independent AI specialists examine a security from their own angle — fundamentals,
            valuation, risk, macro, sentiment — and a Devil&rsquo;s Advocate argues against the
            position. You see the evidence, the disagreement and what would change the picture.
          </p>

          <SessionStarter />

          <p className="microNote">
            Research output only. AIC does not manage money, execute trades, promise results,
            or tell you how much to invest.
          </p>
        </div>

        <div className="previewCard">
          <span className="liveDot">EXAMPLE SESSION</span>
          <h2>NVDA &middot; research view</h2>
          <div className="decision">STAGED ENTRY</div>
          <div className="metric"><span>Committee agreement</span><strong>5 of 7</strong></div>
          <div className="metric"><span>Your policy limit</span><strong>2.0% of portfolio</strong></div>
          <div className="metric"><span>Dissent</span><strong>Risk Agent &middot; WAIT</strong></div>
          <p>
            Illustrative only. Figures in a live session come from market data at the time of the
            session and from limits you set yourself.
          </p>
        </div>
      </section>

      <section className="intents">
        <h2 className="sectionHead">What are you considering?</h2>
        <div className="intentGrid">
          <article className="intent live">
            <span className="intentTag">Available now</span>
            <h3>Analyze</h3>
            <p>I know what I want to analyze.</p>
            <small>A single security examined by the full committee, with evidence and dissent.</small>
          </article>
          <a className="intent live intentLink" href="/build">
            <span className="intentTag">Available now</span>
            <h3>Build</h3>
            <p>I have money to invest.</p>
            <small>An allocation plan by sleeve, with the reasoning behind each weight.</small>
          </a>
          <article className="intent soon">
            <span className="intentTag">In development</span>
            <h3>Review</h3>
            <p>I already have a portfolio.</p>
            <small>Exposure and risk across your positions, with prioritised actions.</small>
          </article>
        </div>
      </section>

      <section className="howItWorks">
        <h2 className="sectionHead">What the committee produces</h2>
        <ul>
          <li><b>Evidence</b> — every material claim carries a source and the date it is as of.</li>
          <li><b>Disagreement</b> — members who dissent are named, with their reasoning.</li>
          <li><b>Your own limits</b> — position size is bounded by constraints you define, computed arithmetically.</li>
          <li><b>Explained confidence</b> — the score is broken down, not asserted.</li>
          <li><b>Conditions</b> — what would have to change for the conclusion to change.</li>
          <li><b>Deferral</b> — when current data is insufficient, the committee says so instead of guessing.</li>
          <li><b>A permanent report</b> — every session leaves a versioned record you can return to.</li>
        </ul>
      </section>

      <section className="disclosure">
        <h2>Important disclosure</h2>
        <p>
          AI Investment Committee is an AI-powered research and decision-support tool. It is not an
          investment adviser, broker-dealer or financial planner, and nothing it produces is
          investment, legal, tax or accounting advice or a recommendation to buy, sell or hold any
          security.
        </p>
        <p>
          Output is generated by AI models from third-party market data and may be incomplete,
          outdated or wrong. Data is provided by Finnhub and is not guaranteed to be accurate or
          timely. Committee members are fictional personas, not licensed analysts.
        </p>
        <p>
          Any limits shown are derived from constraints you enter yourself; they describe your own
          stated policy, not a recommendation about how much to invest. Past performance does not
          indicate future results, and all investing involves risk of loss. You are solely
          responsible for your investment decisions and should consider consulting a licensed
          financial professional in your jurisdiction.
        </p>
      </section>

      <footer className="siteFoot">
        <a href="/terms">Terms of Service</a>
        <a href="/privacy">Privacy Policy</a>
        <a href="/disclosures">Risk &amp; AI Disclosure</a>
        <span>AI-generated research and decision support · not investment advice</span>
      </footer>

      <PremiumMarketDeck />
    </main>
  );
}
