import Link from "next/link";

/**
 * Positioning: research and decision-support, not investment advice.
 * No personal amounts, no promised outcomes, no "we recommend you buy".
 * The committee produces evidence, scenarios and dissent; the user decides.
 */
export default function HomePage() {
  return (
    <main className="landing">
      <nav className="nav">
        <div className="brand">AIC</div>
        <span>AI Investment Committee</span>
        <Link className="ghostButton" href="/committee">Open committee</Link>
      </nav>

      <section className="hero">
        <div>
          <p className="eyebrow">AI INVESTMENT RESEARCH &amp; DECISION SUPPORT</p>
          <h1>Seven analysts argue.<br />You decide.</h1>
          <p className="lede">
            Independent AI specialists examine a stock from their own angle — fundamentals, valuation,
            risk, macro, sentiment — and a Red Team argues against the position. You see the evidence,
            the disagreement and what would change the picture.
          </p>
          <Link className="primaryButton" href="/committee">Open a research session</Link>
          <p className="microNote">
            Research output only. AIC does not manage money, execute trades, promise results,
            or tell you how much to invest.
          </p>
        </div>

        <div className="previewCard">
          <span className="liveDot">EXAMPLE SESSION</span>
          <h2>NVDA · research view</h2>
          <div className="decision">STAGED ENTRY</div>
          <div className="metric"><span>Committee agreement</span><strong>5 of 7</strong></div>
          <div className="metric"><span>Your policy limit</span><strong>2.0% of portfolio</strong></div>
          <div className="metric"><span>Dissent</span><strong>Risk Officer · WAIT</strong></div>
          <p>
            Illustrative only. Figures shown in a live session come from market data at the time of
            the session and from limits you set yourself.
          </p>
        </div>
      </section>

      <section className="howItWorks">
        <h2>What the committee produces</h2>
        <ul>
          <li><b>Evidence</b> — every material claim carries a source and the date it is as of.</li>
          <li><b>Scenarios</b> — bull, base and bear cases with the assumptions behind each.</li>
          <li><b>Dissent</b> — members who disagreed are named, with their reasoning.</li>
          <li><b>Your own limits</b> — position size is bounded by constraints you define, computed arithmetically.</li>
          <li><b>Conditions</b> — what would have to change for the conclusion to change.</li>
          <li><b>Deferral</b> — when current data is insufficient, the committee says so instead of guessing.</li>
        </ul>
      </section>

      <section className="disclosure">
        <h2>Important disclosure</h2>
        <p>
          AI Investment Committee is an AI-powered research and decision-support tool. It is not an
          investment adviser, broker-dealer or financial planner, and nothing it produces is
          investment, legal, tax or accounting advice or a recommendation to buy, sell or hold any
          security.
        </p>
        <p>
          Output is generated by AI models from third-party market data and may be incomplete,
          outdated or wrong. Data is provided by Finnhub and is not guaranteed to be accurate or
          timely. Spoken analysis uses synthetic AI voices; committee members are fictional personas,
          not real analysts.
        </p>
        <p>
          Any limits shown are derived from constraints you enter yourself; they describe your own
          stated policy, not a recommendation about how much to invest. Past performance does not
          indicate future results, and all investing involves risk of loss. You are solely
          responsible for your investment decisions and should consider consulting a licensed
          financial professional in your jurisdiction.
        </p>
      </section>
    </main>
  );
}
