"use client";

import { useEffect, useMemo, useState } from "react";

type Lang="en"|"ru"|"es"|"fr"|"de"|"it"|"pt"|"ar"|"tr"|"az";

const languages:Record<Lang,{label:string;voice:string;dir:"ltr"|"rtl"}>={
  en:{label:"English",voice:"en-US",dir:"ltr"},ru:{label:"Русский",voice:"ru-RU",dir:"ltr"},es:{label:"Español",voice:"es-ES",dir:"ltr"},fr:{label:"Français",voice:"fr-FR",dir:"ltr"},de:{label:"Deutsch",voice:"de-DE",dir:"ltr"},it:{label:"Italiano",voice:"it-IT",dir:"ltr"},pt:{label:"Português",voice:"pt-BR",dir:"ltr"},ar:{label:"العربية",voice:"ar-SA",dir:"rtl"},tr:{label:"Türkçe",voice:"tr-TR",dir:"ltr"},az:{label:"Azərbaycan dili",voice:"az-AZ",dir:"ltr"}
};

const ui:Record<Lang,Record<string,string>>={
  en:{},
  ru:{"AI INVESTMENT COMMITTEE":"ИНВЕСТИЦИОННЫЙ AI-КОМИТЕТ","PRIVATE COMMITTEE ROOM":"ЗАКРЫТЫЙ ЗАЛ КОМИТЕТА","Professional Session":"Профессиональная сессия","Voice on":"Голос включён","Voice off":"Голос выключен","Live debate":"Живое обсуждение","Decision ready":"Решение готово","Awaiting proposal":"Ожидание предложения","SESSION INFO":"ИНФОРМАЦИЯ О СЕССИИ","Asset":"Актив","Session Type":"Тип сессии","Professional debate":"Профессиональное обсуждение","Investment":"Инвестиция","Portfolio":"Портфель","End session":"Завершить сессию","COMMITTEE STATUS":"СТАТУС КОМИТЕТА","Session opened":"Сессия открыта","Complete":"Завершено","Active":"Активно","Voting":"Голосование","Pending":"Ожидание","Decision":"Решение","LIVE COMMITTEE DISCUSSION":"ЖИВОЕ ОБСУЖДЕНИЕ КОМИТЕТА","FINAL RECOMMENDATION":"ИТОГОВАЯ РЕКОМЕНДАЦИЯ","CONFIDENCE":"УВЕРЕННОСТЬ","AGREEMENT":"СОГЛАСИЕ","ALLOCATION":"ДОЛЯ","VOTING SUMMARY":"ИТОГИ ГОЛОСОВАНИЯ","NEXT STEPS":"СЛЕДУЮЩИЕ ШАГИ","Monitor thesis":"Контролировать тезис","Ongoing":"Постоянно","Review risk triggers":"Проверить риск-триггеры","30 days":"30 дней","Reassess allocation":"Пересмотреть долю","Quarterly":"Ежеквартально","Request the floor":"Взять слово","View full report":"Открыть полный отчёт","NEW COMMITTEE SESSION":"НОВАЯ СЕССИЯ КОМИТЕТА","Open investment proposal":"Открыть инвестиционное предложение","Ticker":"Тикер","Investment amount":"Сумма инвестиции","Portfolio value":"Стоимость портфеля","Sector exposure %":"Доля сектора %","Horizon, years":"Горизонт, лет","Risk tolerance":"Допустимый риск","Start committee":"Начать заседание","Committee in session...":"Комитет заседает...","Waiting":"Ожидание","Listening":"Слушает","Speaking":"Говорит","Response":"Ответ","Interruption":"Перебивание","Live":"В эфире"},
  es:{"Professional Session":"Sesión profesional","Voice on":"Voz activa","Voice off":"Voz desactivada","Live debate":"Debate en vivo","Decision ready":"Decisión lista","Awaiting proposal":"Esperando propuesta","SESSION INFO":"INFORMACIÓN DE LA SESIÓN","Asset":"Activo","Investment":"Inversión","Portfolio":"Cartera","End session":"Finalizar sesión","COMMITTEE STATUS":"ESTADO DEL COMITÉ","Voting":"Votación","Decision":"Decisión","LIVE COMMITTEE DISCUSSION":"DEBATE EN VIVO DEL COMITÉ","FINAL RECOMMENDATION":"RECOMENDACIÓN FINAL","CONFIDENCE":"CONFIANZA","AGREEMENT":"ACUERDO","ALLOCATION":"ASIGNACIÓN","VOTING SUMMARY":"RESUMEN DE VOTOS","NEXT STEPS":"PRÓXIMOS PASOS","Request the floor":"Pedir la palabra","View full report":"Ver informe completo","Open investment proposal":"Abrir propuesta de inversión","Start committee":"Iniciar comité"},
  fr:{"Professional Session":"Session professionnelle","Voice on":"Voix activée","Voice off":"Voix désactivée","Live debate":"Débat en direct","Decision ready":"Décision prête","Awaiting proposal":"En attente de proposition","SESSION INFO":"INFORMATIONS DE SESSION","Asset":"Actif","Investment":"Investissement","Portfolio":"Portefeuille","End session":"Terminer la session","COMMITTEE STATUS":"STATUT DU COMITÉ","Voting":"Vote","Decision":"Décision","LIVE COMMITTEE DISCUSSION":"DISCUSSION EN DIRECT","FINAL RECOMMENDATION":"RECOMMANDATION FINALE","CONFIDENCE":"CONFIANCE","AGREEMENT":"ACCORD","ALLOCATION":"ALLOCATION","VOTING SUMMARY":"RÉSUMÉ DES VOTES","NEXT STEPS":"PROCHAINES ÉTAPES","Request the floor":"Demander la parole","View full report":"Voir le rapport complet","Open investment proposal":"Ouvrir une proposition d’investissement","Start committee":"Démarrer le comité"},
  de:{"Professional Session":"Professionelle Sitzung","Voice on":"Stimme an","Voice off":"Stimme aus","Live debate":"Live-Debatte","Decision ready":"Entscheidung bereit","Awaiting proposal":"Warte auf Vorschlag","SESSION INFO":"SITZUNGSINFO","Asset":"Anlage","Investment":"Investition","Portfolio":"Portfolio","End session":"Sitzung beenden","COMMITTEE STATUS":"AUSSCHUSSSTATUS","Voting":"Abstimmung","Decision":"Entscheidung","LIVE COMMITTEE DISCUSSION":"LIVE-AUSSCHUSSDISKUSSION","FINAL RECOMMENDATION":"ENDGÜLTIGE EMPFEHLUNG","CONFIDENCE":"KONFIDENZ","AGREEMENT":"ZUSTIMMUNG","ALLOCATION":"ALLOKATION","VOTING SUMMARY":"ABSTIMMUNGSÜBERSICHT","NEXT STEPS":"NÄCHSTE SCHRITTE","Request the floor":"Wortmeldung","View full report":"Vollständigen Bericht anzeigen","Open investment proposal":"Investitionsvorschlag öffnen","Start committee":"Ausschuss starten"},
  it:{"Professional Session":"Sessione professionale","Voice on":"Voce attiva","Voice off":"Voce disattivata","Live debate":"Dibattito dal vivo","Decision ready":"Decisione pronta","Awaiting proposal":"In attesa della proposta","SESSION INFO":"INFO SESSIONE","Asset":"Asset","Investment":"Investimento","Portfolio":"Portafoglio","End session":"Termina sessione","COMMITTEE STATUS":"STATO DEL COMITATO","Voting":"Votazione","Decision":"Decisione","LIVE COMMITTEE DISCUSSION":"DISCUSSIONE DAL VIVO","FINAL RECOMMENDATION":"RACCOMANDAZIONE FINALE","CONFIDENCE":"FIDUCIA","AGREEMENT":"ACCORDO","ALLOCATION":"ALLOCAZIONE","VOTING SUMMARY":"RIEPILOGO VOTI","NEXT STEPS":"PROSSIMI PASSI","Request the floor":"Chiedi la parola","View full report":"Visualizza rapporto completo","Open investment proposal":"Apri proposta di investimento","Start committee":"Avvia comitato"},
  pt:{"Professional Session":"Sessão profissional","Voice on":"Voz ativada","Voice off":"Voz desativada","Live debate":"Debate ao vivo","Decision ready":"Decisão pronta","Awaiting proposal":"Aguardando proposta","SESSION INFO":"INFORMAÇÕES DA SESSÃO","Asset":"Ativo","Investment":"Investimento","Portfolio":"Portfólio","End session":"Encerrar sessão","COMMITTEE STATUS":"STATUS DO COMITÊ","Voting":"Votação","Decision":"Decisão","LIVE COMMITTEE DISCUSSION":"DISCUSSÃO AO VIVO","FINAL RECOMMENDATION":"RECOMENDAÇÃO FINAL","CONFIDENCE":"CONFIANÇA","AGREEMENT":"ACORDO","ALLOCATION":"ALOCAÇÃO","VOTING SUMMARY":"RESUMO DA VOTAÇÃO","NEXT STEPS":"PRÓXIMOS PASSOS","Request the floor":"Pedir a palavra","View full report":"Ver relatório completo","Open investment proposal":"Abrir proposta de investimento","Start committee":"Iniciar comitê"},
  ar:{"Professional Session":"جلسة احترافية","Voice on":"الصوت مفعل","Voice off":"الصوت متوقف","Live debate":"نقاش مباشر","Decision ready":"القرار جاهز","Awaiting proposal":"بانتظار المقترح","SESSION INFO":"معلومات الجلسة","Asset":"الأصل","Investment":"الاستثمار","Portfolio":"المحفظة","End session":"إنهاء الجلسة","COMMITTEE STATUS":"حالة اللجنة","Voting":"التصويت","Decision":"القرار","LIVE COMMITTEE DISCUSSION":"مناقشة اللجنة المباشرة","FINAL RECOMMENDATION":"التوصية النهائية","CONFIDENCE":"الثقة","AGREEMENT":"الاتفاق","ALLOCATION":"التخصيص","VOTING SUMMARY":"ملخص التصويت","NEXT STEPS":"الخطوات التالية","Request the floor":"طلب الكلمة","View full report":"عرض التقرير الكامل","Open investment proposal":"فتح مقترح استثماري","Start committee":"بدء اللجنة"},
  tr:{"Professional Session":"Profesyonel oturum","Voice on":"Ses açık","Voice off":"Ses kapalı","Live debate":"Canlı tartışma","Decision ready":"Karar hazır","Awaiting proposal":"Teklif bekleniyor","SESSION INFO":"OTURUM BİLGİSİ","Asset":"Varlık","Investment":"Yatırım","Portfolio":"Portföy","End session":"Oturumu bitir","COMMITTEE STATUS":"KOMİTE DURUMU","Voting":"Oylama","Decision":"Karar","LIVE COMMITTEE DISCUSSION":"CANLI KOMİTE TARTIŞMASI","FINAL RECOMMENDATION":"NİHAİ TAVSİYE","CONFIDENCE":"GÜVEN","AGREEMENT":"UZLAŞI","ALLOCATION":"TAHSİS","VOTING SUMMARY":"OY ÖZETİ","NEXT STEPS":"SONRAKİ ADIMLAR","Request the floor":"Söz iste","View full report":"Tam raporu görüntüle","Open investment proposal":"Yatırım teklifini aç","Start committee":"Komiteyi başlat"},
  az:{"Professional Session":"Peşəkar sessiya","Voice on":"Səs aktivdir","Voice off":"Səs söndürülüb","Live debate":"Canlı müzakirə","Decision ready":"Qərar hazırdır","Awaiting proposal":"Təklif gözlənilir","SESSION INFO":"SESSİYA MƏLUMATI","Asset":"Aktiv","Investment":"İnvestisiya","Portfolio":"Portfel","End session":"Sessiyanı bitir","COMMITTEE STATUS":"KOMİTƏ STATUSU","Voting":"Səsvermə","Decision":"Qərar","LIVE COMMITTEE DISCUSSION":"CANLI KOMİTƏ MÜZAKİRƏSİ","FINAL RECOMMENDATION":"YEKUN TÖVSİYƏ","CONFIDENCE":"ƏMİNLİK","AGREEMENT":"RAZILIQ","ALLOCATION":"BÖLGÜ","VOTING SUMMARY":"SƏSVERMƏ XÜLASƏSİ","NEXT STEPS":"NÖVBƏTİ ADDIMLAR","Request the floor":"Söz istə","View full report":"Tam hesabatı aç","Open investment proposal":"İnvestisiya təklifini aç","Start committee":"Komitəni başlat"}
};

function translateText(text:string,lang:Lang){const clean=text.trim();const exact=ui[lang][clean];if(exact)return text.replace(clean,exact);return text;}

export function LanguageController(){
  const [lang,setLang]=useState<Lang>("en");
  const options=useMemo(()=>Object.entries(languages) as [Lang,(typeof languages)[Lang]][],[]);

  useEffect(()=>{const saved=(localStorage.getItem("aic-language") as Lang)||"en";setLang(languages[saved]?saved:"en")},[]);

  useEffect(()=>{
    localStorage.setItem("aic-language",lang);document.documentElement.lang=lang;document.documentElement.dir=languages[lang].dir;
    const originalFetch=window.fetch.bind(window);
    const patched:typeof window.fetch=async(input,init)=>{
      const url=typeof input==="string"?input:input instanceof URL?input.toString():input.url;
      if(init?.body&&typeof init.body==="string"&&(url.includes("/api/committee/sessions")||url.includes("/api/voice"))){
        try{const body=JSON.parse(init.body);body.language=url.includes("/api/voice")?languages[lang].voice:lang;init={...init,body:JSON.stringify(body)}}catch{}
      }
      return originalFetch(input,init);
    };
    window.fetch=patched;

    const apply=()=>{const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);const nodes:Text[]=[];while(walker.nextNode())nodes.push(walker.currentNode as Text);for(const n of nodes){if(n.parentElement?.closest("select,option,script,style"))continue;const next=translateText(n.nodeValue||"",lang);if(next!==n.nodeValue)n.nodeValue=next}};
    apply();const observer=new MutationObserver(()=>requestAnimationFrame(apply));observer.observe(document.body,{subtree:true,childList:true,characterData:true});
    return()=>{observer.disconnect();window.fetch=originalFetch};
  },[lang]);

  return <div style={{position:"fixed",right:18,bottom:18,zIndex:1000}}><select aria-label="Language" value={lang} onChange={e=>setLang(e.target.value as Lang)} style={{minWidth:170,padding:"11px 36px 11px 12px",borderRadius:10,border:"1px solid #324550",background:"rgba(5,12,17,.96)",color:"#fff",fontWeight:700,boxShadow:"0 12px 35px rgba(0,0,0,.45)"}}>{options.map(([code,item])=><option key={code} value={code}>{item.label}</option>)}</select></div>
}
