import Link from "next/link";
import "../legal/legal.css";

export const metadata = {
  title: "Terms of Service — AI Investment Committee",
  description: "Terms governing the use of the AIC research and decision-support platform."
};

/**
 * DRAFT for review by qualified counsel.
 *
 * Written from what the product actually does, so a lawyer does not have to
 * reverse-engineer the system. Every operator-specific value is marked and must
 * be completed before publication.
 */
export default function TermsPage() {
  return (
    <main className="legal">
      <header className="legalHead">
        <p className="legalKicker"><Link href="/">AIC</Link> · Legal</p>
        <h1>Terms of Service</h1>
        <p className="legalDates">
          Draft · Last updated <span className="fill">[DATE]</span> · Effective <span className="fill">[DATE]</span>
        </p>
      </header>

      <div className="legalDraft">
        <h2>Draft — not yet reviewed by counsel</h2>
        <p>
          This document was prepared from the platform&rsquo;s actual behaviour as a starting point
          for legal review. It is not legal advice and has not been reviewed by a qualified lawyer.
          Investment-related services are regulated, and requirements differ by country and by
          US state.
        </p>
        <p>
          Before publishing: have securities counsel review this document and the platform&rsquo;s
          positioning, and complete every <span className="fill">[marked]</span> field.
        </p>
      </div>

      <h2>1. Who we are</h2>
      <p>
        AI Investment Committee (&ldquo;AIC&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;) is operated
        by <span className="fill">[LEGAL ENTITY NAME]</span>, registered in{" "}
        <span className="fill">[JURISDICTION]</span> at <span className="fill">[REGISTERED ADDRESS]</span>.
        You can reach us at <span className="fill">[CONTACT EMAIL]</span>.
      </p>

      <h2>2. What AIC is — and what it is not</h2>
      <p>
        AIC is an AI-powered research and decision-support tool. Several AI agents examine a
        security from different perspectives, disagree with each other, and produce a written
        record with sources.
      </p>
      <p><strong>AIC is not, and does not act as:</strong></p>
      <ul>
        <li>an investment adviser, broker-dealer, or financial planner;</li>
        <li>a custodian &mdash; we never hold, manage or have access to your money or securities;</li>
        <li>an execution venue &mdash; we do not place, route or execute trades.</li>
      </ul>
      <p>
        Nothing produced by AIC is investment, legal, tax or accounting advice, or a recommendation
        or solicitation to buy, sell or hold any security. Output is research material. Every
        investment decision is yours alone, and you should consider consulting a licensed
        professional in your jurisdiction.
      </p>

      <h2>3. Eligibility</h2>
      <p>
        You must be at least 18 years old and legally able to enter into these terms. You may not
        use AIC where doing so would breach any law applying to you. We may restrict access from
        particular jurisdictions at any time.
      </p>

      <h2>4. Position limits are your own figures</h2>
      <p>
        AIC computes a maximum position size from constraints <em>you</em> enter &mdash; portfolio
        value, sector exposure, horizon and risk tolerance. That figure describes the limit implied
        by your own stated policy. It is not advice about how much to invest, and it is only as
        accurate as the numbers you supply. Where you leave an input blank, the corresponding
        constraint is recorded as not assessed and is not applied.
      </p>

      <h2>5. AI-generated output and its limits</h2>
      <p>
        Committee members are fictional personas, not real analysts, and hold no qualifications or
        licences. Their statements are generated by AI language models and may be incomplete,
        outdated, mistaken, or internally inconsistent. Models can produce plausible statements that
        are wrong.
      </p>
      <p>
        We do not warrant the accuracy, completeness or timeliness of any output, and we make no
        promise, projection or guarantee about investment performance. Past performance does not
        indicate future results. All investing carries the risk of loss, including total loss.
      </p>

      <h2>6. Market data</h2>
      <p>
        Market data and news are supplied by third parties, currently Finnhub. We do not control
        that data and do not guarantee it is accurate, complete or current. Data may be delayed,
        and quotes carry the timestamp reported by the provider. Third-party data remains subject to
        the provider&rsquo;s own terms.
      </p>

      <h2>7. Reviews, plans and payment</h2>
      <p>
        New visitors receive <span className="fill">[NUMBER]</span> free committee reviews. A review
        is consumed when a session produces a decision. Sessions that fail for technical reasons do
        not consume a review. Follow-up questions within an existing session, and reopening a report
        you have already generated, are free.
      </p>
      <p>
        <span className="fill">[Complete once paid plans launch: prices, billing cycle, renewal,
        cancellation, refunds, and the statutory withdrawal rights that apply in your customers&rsquo;
        jurisdictions.]</span>
      </p>

      <h2>8. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>scrape, resell or redistribute output or market data obtained through AIC;</li>
        <li>present AIC output as personalised advice from a licensed professional;</li>
        <li>use AIC to break any securities, sanctions or market-abuse law;</li>
        <li>attempt to circumvent usage limits, security controls or access other users&rsquo; data;</li>
        <li>place automated load on the service beyond normal individual use.</li>
      </ul>

      <h2>9. Availability and changes</h2>
      <p>
        AIC is provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis. We may
        change, suspend or discontinue any part of the service, and we do not guarantee uninterrupted
        availability. Stored reports may be removed in line with our retention practice described in
        the <Link href="/privacy">Privacy Policy</Link>.
      </p>

      <h2>10. Limitation of liability</h2>
      <p>
        To the fullest extent permitted by law, we are not liable for investment losses, lost
        profits, or indirect or consequential loss arising from your use of AIC or reliance on its
        output. <span className="fill">[Counsel to set the liability cap and confirm which
        exclusions are enforceable in your jurisdiction — consumer law in the EU, UK and several US
        states restricts these clauses.]</span>
      </p>

      <h2>11. Intellectual property</h2>
      <p>
        The platform, its interface and its underlying software remain ours. Reports generated from
        your sessions are yours to use for your own purposes; the underlying market data remains
        subject to the data provider&rsquo;s terms.
      </p>

      <h2>12. Changes to these terms</h2>
      <p>
        We may update these terms. Material changes will be reflected in the &ldquo;last
        updated&rdquo; date above and, where required, notified to you. Continuing to use AIC after
        a change means you accept the revised terms.
      </p>

      <h2>13. Governing law</h2>
      <p>
        These terms are governed by the laws of <span className="fill">[JURISDICTION]</span>, and
        disputes are subject to the exclusive jurisdiction of its courts.{" "}
        <span className="fill">[Counsel to confirm — mandatory consumer-protection rules may
        override a choice-of-law clause.]</span>
      </p>

      <footer className="legalFoot">
        <Link href="/">Home</Link>
        <Link href="/privacy">Privacy Policy</Link>
      </footer>
    </main>
  );
}
