export const languages = {
  en: { label: "English", locale: "en-US" }, ru: { label: "Русский", locale: "ru-RU" }, es: { label: "Español", locale: "es-ES" }, fr: { label: "Français", locale: "fr-FR" }, de: { label: "Deutsch", locale: "de-DE" }, it: { label: "Italiano", locale: "it-IT" }, pt: { label: "Português", locale: "pt-BR" }, ar: { label: "العربية", locale: "ar-SA" }, tr: { label: "Türkçe", locale: "tr-TR" }, az: { label: "Azərbaycan dili", locale: "az-AZ" }
} as const;
export type Language = keyof typeof languages;

const ui = {
 en:{proposal:"CLIENT PROPOSAL",open:"Open a committee session",intro:"The committee evaluates the investment against the client's portfolio, risk level and time horizon.",ticker:"Ticker",amount:"Proposed amount ($)",portfolio:"Portfolio value ($)",sector:"Sector exposure (%)",horizon:"Horizon (years)",risk:"Risk tolerance",low:"Low",moderate:"Moderate",high:"High",enter:"Enter committee room",live:"Committee in session…",demo:"Demo analysis only. No trades are executed.",room:"PRIVATE COMMITTEE ROOM",voice:"Preview voice",awaiting:"Awaiting proposal",opening:"Opening session",session:"Committee in session",ready:"Decision ready",waiting:"Waiting",analyzing:"Analyzing",speaking:"Speaking",complete:"Complete",brief:"SESSION BRIEF",equity:"US EQUITY",committeeReady:"The committee is ready",submit:"Submit the proposal to begin a structured investment debate.",final:"FINAL RECOMMENDATION",confidence:"Confidence",suggested:"Suggested amount",allocation:"Allocation",progress:"Analysis in progress",record:"MEETING RECORD",discussion:"Committee discussion",back:"Back to room",decision:"Committee decision",vote:"Vote",continue:"Continue discussion",rationale:"View full rationale",newSession:"Start new session",warning:"Demo mode: verified market data must be connected before public release.",client:"Our client is considering",context:"The committee will now assess the opportunity in the context of",portfolioWord:"portfolio."},
 ru:{proposal:"ПРЕДЛОЖЕНИЕ КЛИЕНТА",open:"Открыть заседание комитета",intro:"Комитет оценивает инвестицию с учетом портфеля клиента, уровня риска и инвестиционного горизонта.",ticker:"Тикер",amount:"Сумма инвестиции ($)",portfolio:"Стоимость портфеля ($)",sector:"Доля сектора (%)",horizon:"Горизонт (лет)",risk:"Допустимый риск",low:"Низкий",moderate:"Умеренный",high:"Высокий",enter:"Войти в зал заседаний",live:"Идет заседание…",demo:"Демонстрационный анализ. Сделки не исполняются.",room:"ЗАКРЫТЫЙ ЗАЛ КОМИТЕТА",voice:"Прослушать голос",awaiting:"Ожидается предложение",opening:"Открытие заседания",session:"Идет заседание",ready:"Решение готово",waiting:"Ожидает",analyzing:"Анализирует",speaking:"Говорит",complete:"Завершено",brief:"МАТЕРИАЛЫ ЗАСЕДАНИЯ",equity:"АКЦИЯ США",committeeReady:"Комитет готов",submit:"Отправьте предложение, чтобы начать структурированное обсуждение.",final:"ИТОГОВАЯ РЕКОМЕНДАЦИЯ",confidence:"Уверенность",suggested:"Рекомендуемая сумма",allocation:"Доля портфеля",progress:"Выполняется анализ",record:"ПРОТОКОЛ ЗАСЕДАНИЯ",discussion:"Обсуждение комитета",back:"Вернуться в зал",decision:"Решение комитета",vote:"Голос",continue:"Продолжить обсуждение",rationale:"Посмотреть обоснование",newSession:"Новое заседание",warning:"Демо-режим: перед публичным запуском необходимо подключить проверенные рыночные данные.",client:"Наш клиент рассматривает инвестицию",context:"Комитет оценит возможность в контексте портфеля стоимостью",portfolioWord:"."},
 es:{proposal:"PROPUESTA DEL CLIENTE",open:"Abrir una sesión del comité",intro:"El comité evalúa la inversión según la cartera, el riesgo y el horizonte del cliente.",ticker:"Símbolo",amount:"Importe propuesto ($)",portfolio:"Valor de la cartera ($)",sector:"Exposición sectorial (%)",horizon:"Horizonte (años)",risk:"Tolerancia al riesgo",low:"Baja",moderate:"Moderada",high:"Alta",enter:"Entrar a la sala",live:"Comité en sesión…",demo:"Análisis de demostración. No se ejecutan operaciones.",room:"SALA PRIVADA DEL COMITÉ",voice:"Vista previa de voz",awaiting:"Esperando propuesta",opening:"Abriendo sesión",session:"Comité en sesión",ready:"Decisión lista",waiting:"En espera",analyzing:"Analizando",speaking:"Hablando",complete:"Completo",brief:"RESUMEN DE SESIÓN",equity:"ACCIÓN DE EE. UU.",committeeReady:"El comité está listo",submit:"Envíe la propuesta para iniciar el debate.",final:"RECOMENDACIÓN FINAL",confidence:"Confianza",suggested:"Importe sugerido",allocation:"Asignación",progress:"Análisis en curso",record:"ACTA DE LA REUNIÓN",discussion:"Discusión del comité",back:"Volver a la sala",decision:"Decisión del comité",vote:"Voto",continue:"Continuar discusión",rationale:"Ver justificación",newSession:"Nueva sesión",warning:"Modo demo: conecte datos de mercado verificados antes del lanzamiento.",client:"Nuestro cliente considera una inversión de",context:"El comité evaluará la oportunidad dentro de una cartera de",portfolioWord:"."}
} as const;
export function getUI(language: Language){ return (ui as any)[language] ?? ui.en; }
